name: 0day-monitor 0day监控

on:
  schedule:
    - cron: '0 8 * * *'   # UTC 时间每天早上8点执行
  workflow_dispatch:

jobs:
  crawl-and-update:
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    permissions: #新增：赋予推送代码的权限
      contents: write

    steps:
      - name: 检出仓库
        uses: actions/checkout@v4

      - name: 设置Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 安装依赖
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: 安装Playwright浏览器
        run: |
          python -m playwright install chromium
          python -m playwright install-deps

      - name: 执行爬虫脚本
        run: python vuln_scraper.py

      - name: 获取最新文件
        id: files
        run: |
          JSON_FILE=$(ls vulnerability_reports/vulnerability_report_*.json | sort -r | head -n 1)
          MD_FILE=$(ls vulnerability_reports/vulnerability_report_*.md | sort -r | head -n 1)
          echo "json_file=${JSON_FILE}" >> $GITHUB_OUTPUT
          echo "md_file=${MD_FILE}" >> $GITHUB_OUTPUT

      - name: 拉取远程更新
        run: |
          git pull origin main --rebase

      - name: 自动提交更新
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          # git add -f result/0day_*.json result/0day_*.md
          git add -f  vulnerability_reports/vulnerability_report_*.md  #仅更新md文件
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "自动更新0day: $(date +'%Y-%m-%d %H:%M')"
            git push
          else
            echo "无变更可提交"
          fi

      - name: 邮件发送报告
        uses: dawidd6/action-send-mail@master
        with:
          connection_url: ${{secrets.MAIL_CONNECTION}}
          server_address: smtp.163.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: 漏洞情报报告
          body: ${{ steps.read_mail_content.outputs.content }}
          to: 675372848@qq.com
          from: GitHub Actions
          convert_markdown: true
